pkg/compiler/compiler.go, pkg/compiler/error/errors.go, pkg/compiler/register.go, pkg/compiler/rego/register.go, pkg/compiler/rego/rego.go, pkg/compiler/rego/rego_test.go, pkg/compiler/test/compiler_test.go
```
~/src/github.com/infobloxopen/seal/pkg/compiler/test
=== RUN   TestCompiler
--- PASS: TestCompiler (0.00s)
=== RUN   TestLanguages
TestLanguages: compiler_test.go:84: validate list of languages - supported languages: []string{"rego"}
--- PASS: TestLanguages (0.00s)
PASS
ok  	github.com/infobloxopen/seal/pkg/compiler/test	0.293s
```
```
~/src/github.com/infobloxopen/seal/pkg/compiler/rego
TestCompile: rego_test.go:125: validate policy: allow subject group foo to resolve dns.request;
TestCompile: rego_test.go:126: rego language output generated:
package foo
allow = true {
`foo` in input.subject.groups
input.verb == `resolve`
re_match(`dns.request`, input.type)
}
--- PASS: TestCompile (0.00s)
PASS
ok  	github.com/infobloxopen/seal/pkg/compiler/rego	0.104s
```
=> added pkg/compiler/rego

docs/source/examples/simple/products.inventory.opa, docs/source/examples/simple/products.inventory.seal, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go
```
go build
allow subject group everyone to inspect products.inventory;
allow subject group operators to use products.inventory;
allow subject group admins to manage products.inventory;
allow subject user cto@acme.com to manage products.inventory;
```
=> allow email for subject user

docs/source/examples/simple/products.inventory.opa, docs/source/examples/simple/products.inventory.seal, pkg/compiler/test/policy_compiler_test.go, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go, pkg/token/token.go
example of policy with a comment:
```
...
allow subject user cto@acme.com to manage products.inventory;
```
=> GH-53: use # through end of line as comments in seal policy

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.seal, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/parser.go
`allow subject group customers to buy petstore.pet where ctx.status == "available";` 
```
./seal compile -s docs/source/examples/petstore/petstore.all.swagger -f docs/source/examples/petstore/petstore.all.seal | tee docs/source/examples/petstore/petstore.all.rego
...
allow {
seal_list_contains(input.subject.groups, `customers`)
input.status == "available"
}
...
gidata.petstore.all.test_banned_deny: PASS (459.4µs)
data.petstore.all.test_banned_deny_negative: PASS (217.1µs)
data.petstore.all.test_inspect: PASS (290.9µs)
data.petstore.all.test_inspect_negative: PASS (222.7µs)
data.petstore.all.test_read: PASS (257µs)
data.petstore.all.test_read_negative: PASS (318µs)
data.petstore.all.test_manage_cto: PASS (314.3µs) …
```
=> GH-57: rego compiler generates valid rego for simple where clause

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.swagger, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go, pkg/parser/parser.go, pkg/token/token.go
`deny subject group managers to sell petstore.pet where ctx.status != "available";`
```
./seal compile -s docs/source/examples/petstore/petstore.all.swagger -f docs/source/examples/petstore/petstore.all.seal | tee docs/source/examples/petstore/petstore.all.rego
...
deny {
seal_list_contains(input.subject.groups, `managers`)
input.verb == `sell`
input.status != "available"
}
...
```
one to one mapping of SEAL and OPA Comparison Operators:
https://www.openpolicyagent.org/docs/latest/policy-language/#comparison-operators
```
a  ==  b  #  `a` is equal to `b`.
a  !=  b  #  `a` is not equal to `b`.
a  <   b  #  `a` is less than `b`.
a  <=  b  #  `a` is less than or equal to `b`.
a  >   b  #  `a` is greater than `b`.
a  >=  b  #  `a` is greater than or equal …
```
=> GH-44: fixed lexer comparison operators; added simple where clause not equal operator demo

Makefile, docs/source/examples/petstore/petstore.all.rego.compiled, pkg/ast/ast.go, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go, pkg/parser/parser.go, pkg/token/token.go, pkg/types/interface.go, pkg/types/interface_test.go
```
./seal compile -s docs/source/examples/petstore/petstore.all.swagger -f docs/source/examples/petstore/petstore.all.seal | tee docs/source/examples/petstore/petstore.all.rego.compiled
INFO[0000] logging level                                 logging.level=info
...
deny {
seal_list_contains(input.subject.groups, `managers`)
input.verb == `sell`
(input.status != "available")
}
...
allow {
seal_list_contains(input.subject.groups, `customers`)
(input.status == "available")
}
...
PASS: 7/7
+ git diff --exit-code petstore.all.rego petstore.all.test.rego
git diff --exit-code docs/source/examples/petstore
```
=> GH-60: implemented pratt parser for conditionals

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.swagger, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/lexer/lexer_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go, pkg/token/token.go, pkg/token/token_test.go
`allow subject group breeders_maltese to buy petstore.pet where ctx.status == "reserved" and ctx.breed == "maltese";`
```
./seal compile -s docs/source/examples/petstore/petstore.all.swagger -f docs/source/examples/petstore/petstore.all.seal | tee docs/source/examples/petstore/petstore.all.rego.compiled
INFO[0000] logging level                                 logging.level=info
package petstore.all
...
allow {
seal_list_contains(input.subject.groups, `breeders_maltese`)
(input.status == "reserved")
(input.breed == "maltese")
}
...
+ docker run -v /Users/wlu/src/github.com/infobloxopen/seal/docs/source/examples/petstore:/data -w /data openpolicyagent/opa:latest test -v petstore.all.rego petstore.all.test.rego petstore.all.mock.json …
```
=> GH-68: allow `and` as conditional in where clause

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.swagger, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go, pkg/token/token_test.go
`deny subject group fussy to buy petstore.pet where not ctx.neutered and not ctx.potty_trained;`
```
...
deny {
seal_list_contains(input.subject.groups, `fussy`)
not input.neutered
not input.potty_trained
}
...
```
=> GH-43: allow not as conditional in where clause

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, main.go, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go
`allow subject group fussy to buy petstore.pet where not (ctx.neutered and ctx.potty_trained);`
```
...
allow {
seal_list_contains(input.subject.groups, `fussy`)
not line4_not1_cnd
}
line4_not1_cnd {
input.neutered
input.potty_trained
}
...
```
=> GH-72: allow parens as grouped conditions in where clause

Makefile, docs/source/examples/bench-rego.sh, docs/source/examples/check-rego.sh
```
$ make bench
...
+ docker run --rm -v /Users/wlu/src/github.com/infobloxopen/seal/docs/source/examples/petstore:/data -w /data openpolicyagent/opa:latest test -v --bench --count=2 -t 10s petstore.all.rego petstore.all.test.rego petstore.all.mock.json
data.petstore.all.test_banned_deny	   25988	     46659 ns/op	     38229 timer_rego_query_eval_ns/op	   12474 B/op	     218 allocs/op
data.petstore.all.test_banned_deny_negative	   28107	     42348 ns/op	     34318 timer_rego_query_eval_ns/op	   13373 B/op	     223 allocs/op
data.petstore.all.test_inspect	   25960	     46686 ns/op	     38174 timer_rego_query_eval_ns/op	   12385 B/op	     218 allocs/op
data.petstore.all.test_inspect_negative	   26631	     44543 ns/op	     35882 timer_rego_query_eval_ns/op	   13453 B/op	     226 allocs/op …
```
=> added make bench to benchmark rego

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.swagger, docs/source/examples/petstore/petstore.jwt.swagger, pkg/ast/ast.go, pkg/compiler/rego/rego.go, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go, pkg/token/token.go
rule:
```
deny subject group everyone to buy petstore.pet where ctx.age <= 2;
```
test:
```
...
deny {
seal_list_contains(input.subject.groups, `everyone`)
input.age <= 2
}
...
```
=> GH-84: allow integer to be compared in where clause conditional

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.test.rego
old hardcoded jwt was used:
```
test_use_petstore_jwt {
in := {
...
"jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJub3RfcGV0c3RvcmUuY29tIn0.iEsWURIWWbd4LV4UAyU7SPufo9pD5qcGLnCmqxxQExo",
```
generate jwt from claims for use in tests:
```
"jwt": sealtest_jwt_encode_sign({
"iss": "not_petstore.swagger.io",
"sub": "wiley-e-coyote@acme.com",
"groups": ["everyone", "test"],
}),
```
tests pass:
```
...
data.petstore.all.test_use_petstore_jwt: PASS (910.2µs)
data.petstore.all.test_use_petstore_jwt_negative: PASS (552µs)
...
```
=> GH-90: replaced petstore.com with petstore.swagger.io; generate jwt in rego tests

docs/source/examples/petstore/petstore.jwt.swagger
this PR defines the tenant_ref property in the swagger file.  It is the first of others to address support of multi-tenancy.
=> GH-11: added tenant_ref property to petstore.jwt.swagger

pkg/compiler/policy_compiler.go
DEMO:
FATA[0000] could not create policy compiler              error="Swagger yaml unmarshal error: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context:\n# This is a bad swagger, there should be no \"none\" after \"bad.widget:\"\nopenapi: \"3.0.0\"\ncomponents:\n  schemas:\n    allow:\n      type: object\n      properties:\n        notify:\n          type: boolean\n      x-seal-type: action\n    bad.widget: none\n      x-seal-default-action: allow\n      x-seal-actions:\n      - allow\n      x-seal-verbs:\n      - throw\n      - swim\n      type: object\n      properties:\n        id:\n          type: string\n        name:\n          type: string\n\n"
=> GH-119: Return offending swagger yaml in error msg on yaml unmarshal error

docs/source/examples/petstore/petstore.all.swagger, docs/source/key-concepts/introduction.md
documentation for verb to permission mappings should have been a map instead of an array per GH-104
=> GH-104: fixed docs to define verb to permission mappings via maps in swagger

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.swagger, docs/source/examples/petstore/petstore.all.test.rego, pkg/compiler/compiler.go, pkg/compiler/policy_compiler.go, pkg/compiler/rego/rego.go, pkg/compiler/rego/rego_test.go, pkg/compiler/test/compiler_test.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition_test.go, pkg/parser/parser_test.go, pkg/types/types.go, pkg/types/types_test.go
```
$ make test
rego_test.go:174: validate policy: allow subject group foo to manage petstore.pet;
rego_test.go:175: rego language output generated:
package foo
}
allow {
}
[header, payload, signature] := …
```
=> GH-104: Add parsing/rego support for (non-global) verb-permission mappings

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.test.rego, pkg/compiler/rego/rego.go, pkg/compiler/rego/rego_test.go, pkg/compiler/test/policy_compiler_test.go
```
$ make test
package foo
}
allow {
}
obligations := [
]
[header, payload, …
```
=> GH-124: Fix compiled rego for negation (NOT operator)

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, pkg/compiler/error/errors.go, pkg/compiler/rego/rego.go, pkg/compiler/rego/rego_test.go, pkg/compiler/test/policy_compiler_test.go
```
$ make test
package foo
}
allow {
}
obligations := {
}
[header, payload, …
```
=> Change compiled rego obligations structure

cmd/root.go, docs/source/examples/petstore/petstore.all.rego.compiled, pkg/ast/ast.go, pkg/compiler/rego/rego.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition.go, pkg/parser/parser.go, pkg/token/token.go, pkg/types/types.go
Also changed all debug-level logging to trace-level so calling application can enable debug-level without fear of enabling the voluminous/verbose trace-level logging of the seal parser/compiler
```
$ make test
package foo
}
allow { …
```
=> Fix generated obligations for multiple stmts inside context

pkg/parser/condition.go, pkg/parser/condition_test.go
```
$ make test
package foo
}
allow {
}
obligations := {
}
[header, payload, …
```
=> Export parser.ParseCondition() to parse SEAL condition strings

pkg/compiler/sql/sql_condition.go, pkg/compiler/sql/sql_condition_test.go
Add new sqlcompiler.CompileCondition() to support converting of obligations into SQL.
Both `make test` and `make demo` pass successfully.
Output of new unit-tests:
```
$ go test -v
=== RUN   TestCompileCondition
sql_condition_test.go:74: Test#0: success: expected error and got err=no prefix condition parse function for IDENT found
sql_condition_test.go:76: Test#1: success: where=(foobar.qwerty = 'there''s a single-quote in this string')
sql_condition_test.go:76: Test#2: success: where=(mysqltable.nbf < 123 AND (mysqltable.description = 'string with subject. in it'))
sql_condition_test.go:76: Test#3: success: where=((NOT (mysqltable.iss = 'string with ctx. in it')) AND (mysqltable.name ~ '.*goofy.*'))
sql_condition_test.go:74: Test#4: success: expected error and got err=map/array indexing …
```
=> Add exported sqlcompiler.CompileCondition() fn

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, pkg/compiler/rego/rego.go, pkg/compiler/sql/sql_condition.go, pkg/compiler/sql/sql_condition_test.go, pkg/compiler/test/policy_compiler_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go
This PR adds type-information to obligations.  Once this is merged, I'll update
https://github.com/infobloxopen/seal/pull/132
with support for this type-information.
```
$ make test demo
package foo
}
allow { …
```
=> Prefix/annotate obligations with swagger-type

pkg/compiler/sql/sql_condition.go, pkg/compiler/sql/sql_condition_test.go, pkg/compiler/sql/sql_dialect.go, pkg/compiler/sql/sql_typemapper.go, pkg/compiler/sql/sql_typemapper_test.go, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go
Replaces https://github.com/infobloxopen/seal/pull/132 with more developer-friendly SQL API (as requested by @daniel-garcia )
`make test demo` passes successfully.  Pertinent unit-tests shown:
```
$ go test -v
=== RUN   TestNextToken
--- PASS: TestNextToken (0.00s)
=== RUN   TestContextToken
--- PASS: TestContextToken (0.00s)
=== RUN   TestNextTokenComment
--- PASS: TestNextTokenComment (0.00s)
=== RUN   TestIsIndexedIdentifier
lexer_test.go:323: Test#0: success: actual=true
lexer_test.go:323: Test#1: success: actual=true
lexer_test.go:323: Test#2: success: actual=false
lexer_test.go:323: Test#3: success: actual=true
lexer_test.go:323: Test#4: success: actual=true
lexer_test.go:323: Test#5: success: actual=false
--- PASS: TestIsIndexedIdentifier (0.00s)
=== RUN   TestSplitIdentifier …
```
=> Refactor SQL-API to use Type/Property mappers; Add SQL-JSONB-predicate support

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.swagger, docs/source/examples/petstore/petstore.all.test.rego, pkg/compiler/sql/sql_condition_test.go, pkg/compiler/test/policy_compiler_test.go, pkg/lexer/lexer.go
```
$ make test demo
package foo
}
allow {
}
obligations := {
}
[header, payload, …
```
=> GH-135: Add support for alphanumeric identifiers

docs/source/examples/petstore/petstore.all.rego, docs/source/examples/petstore/petstore.all.rego.compiled, docs/source/examples/petstore/petstore.all.seal, docs/source/examples/petstore/petstore.all.test.rego, docs/source/grammar/grammar.md, pkg/ast/ast.go, pkg/compiler/policy_compiler.go, pkg/compiler/rego/rego.go, pkg/compiler/rego/rego_test.go, pkg/compiler/sql/sql_condition.go, pkg/compiler/sql/sql_condition_test.go, pkg/compiler/test/policy_compiler_test.go, pkg/lexer/lexer.go, pkg/lexer/lexer_test.go, pkg/parser/condition.go, pkg/parser/condition_test.go, pkg/parser/parser.go, pkg/token/token.go, pkg/token/token_test.go
Also add WithInputName() method to Rego compiler
```
seal$ go test ./...
ok      github.com/infobloxopen/seal/pkg/compiler/rego  0.005s
ok      github.com/infobloxopen/seal/pkg/compiler/sql   0.006s
ok      github.com/infobloxopen/seal/pkg/compiler/test  0.073s
ok      github.com/infobloxopen/seal/pkg/lexer  0.028s
ok      github.com/infobloxopen/seal/pkg/parser 0.005s
ok      github.com/infobloxopen/seal/pkg/token  0.005s
ok …
```
=> Add array-literal support for in-operator
